const products = [
    {
        id: 1,
        image: 'https://example.com/product1.jpg',
        name: 'Smartphone',
        price: 599.99,
        originalPrice: 699.99,
        discount: '15% OFF',
        hot: true,
        soldOut: false,
        rating: 4,
        reviews: 145,
    },
    {
        id: 2,
        image: 'https://example.com/product2.jpg',
        name: 'Laptop',
        price: 999.99,
        originalPrice: 1199.99,
        discount: '20% OFF',
        hot: false,
        soldOut: false,
        rating: 5,
        reviews: 200,
    },
    {
        id: 3,
        image: 'https://example.com/product3.jpg',
        name: 'Headphones',
        price: 199.99,
        originalPrice: 249.99,
        discount: '10% OFF',
        hot: false,
        soldOut: true,
        rating: 3,
        reviews: 80,
    },
    {
        id: 4,
        image: 'https://example.com/product4.jpg',
        name: 'Smartwatch',
        price: 149.99,
        originalPrice: 179.99,
        discount: '17% OFF',
        hot: true,
        soldOut: false,
        rating: 4,
        reviews: 300,
    },
    {
        id: 5,
        image: 'https://example.com/product5.jpg',
        name: 'Camera',
        price: 499.99,
        originalPrice: 599.99,
        discount: '10% OFF',
        hot: false,
        soldOut: false,
        rating: 4,
        reviews: 110,
    },
    {
        id: 6,
        image: 'https://example.com/product6.jpg',
        name: 'Tablet',
        price: 299.99,
        originalPrice: 349.99,
        discount: '14% OFF',
        hot: true,
        soldOut: true,
        rating: 3,
        reviews: 75,
    },
    {
        id: 7,
        image: 'https://example.com/product7.jpg',
        name: 'Wireless Earbuds',
        price: 99.99,
        originalPrice: 129.99,
        discount: '23% OFF',
        hot: false,
        soldOut: false,
        rating: 5,
        reviews: 230,
    },
    {
        id: 8,
        image: 'https://example.com/product8.jpg',
        name: 'Gaming Console',
        price: 399.99,
        originalPrice: 449.99,
        discount: '11% OFF',
        hot: true,
        soldOut: true,
        rating: 4,
        reviews: 150,
    },
    {
        id: 9,
        image: 'https://example.com/product9.jpg',
        name: '4K TV',
        price: 799.99,
        originalPrice: 999.99,
        discount: '25% OFF',
        hot: false,
        soldOut: false,
        rating: 4,
        reviews: 175,
    },
    {
        id: 10,
        image: 'https://example.com/product10.jpg',
        name: 'Bluetooth Speaker',
        price: 149.99,
        originalPrice: 199.99,
        discount: '20% OFF',
        hot: false,
        soldOut: false,
        rating: 3,
        reviews: 95,
    }
];

export default products;
