/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './header';
import Footer from './footer';

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    // <div className="flex overflow-hidden flex-col  bg-white">
    <div className="flex flex-col px-5 md:mx-16 mx-4 font-urbanist">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
